In [2]:
import numpy as np

def FindCoefficients (points, der_order, h):
    
    if der_order+1!=len(points):
        return 'No se puede hacer'
    
    m = np.zeros((len(points), len(points)))
    n = np.zeros(len(points))
     
    for i in range(der_order+1):
        for j in range(der_order+1):
            m[i][j]=(points[j])**i
            
    for i in range(der_order+1):
        if i==(der_order):
            n[i] = np.math.factorial(der_order)
    
    M = np.linalg.inv(m)*n
    
    return M
        
print(FindCoefficients ([-2, -1, 0, 1, 2], 4, 1))

[[ 0.  0. -0. -0.  1.]
 [ 0. -0.  0.  0. -4.]
 [ 0.  0. -0.  0.  6.]
 [ 0.  0.  0. -0. -4.]
 [ 0. -0. -0.  0.  1.]]
