In [1]:
import numpy as np

In [4]:
A = np.array([[1,2,-1], [1,0,1], [4,-4,5]])

In [6]:
# los vectores propios estan dados en columnas
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [38]:
def EigValue (A, c=0, itmax=1000, tolerancia=1e-20):
    n = A.shape[0]
    v0 = np.zeros(n)
    v0[c] = 1
    lambda1 = 0
    
    for k in range(itmax): 
        v1 = np.dot(A,v0)
        v1 = v1/np.linalg.norm(v1) 
        
        v2 = np.dot(A,v1)
        v2 = v2/np.linalg.norm(v1)
        
        lambda0 = lambda1
        lambda1 = v2[0]/v1[0] #fórmula 5.56 de las notas
        
        v0 = v2
        
        if np.abs(lambda0 - lambda1) <= tolerancia:
            break
        
    return lambda1, v1

In [39]:
value1, vector1 = EigValue(A)
print(value1, vector1)

3.0 [-0.23570226  0.23570226  0.94280904]


In [40]:
def Tensor(v):
    n = v.shape[0]
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            T[i,j] = v[i]*v[j]
            
    return T

In [51]:
v1 = np.array([1,0])
Tensor(v1)

array([[1., 0.],
       [0., 0.]])

$$B = A -\lambda_1 \vec{v}_1\otimes\vec{v}_1$$

In [55]:
Tensor1 = Tensor(vector1)

In [56]:
B = A - value1*Tensor1

In [57]:
B

array([[ 0.83333333,  2.16666667, -0.33333333],
       [ 1.16666667, -0.16666667,  0.33333333],
       [ 4.66666667, -4.66666667,  2.33333333]])

In [67]:
EigValue(B)

(1.9999999999999991, array([0.17069719, 0.23897606, 0.95590424]))

In [68]:
value2, vector2 = EigValue(B)
Tensor2 = Tensor(vector2)

In [69]:
C = B-value2*Tensor2

In [72]:
value2

1.9999999999999991

In [71]:
value3, vector3 = EigValue(C)
value3

1.000000000000002