In [369]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
from scipy import integrate
import scipy.linalg

Ejercicios: Álgebra lineal

Problemas: 3,4,5,6,7,9,10,12,13,14,15

Listos: 3,6,7,9,  ,15

## Punto 3. Algoritmo para mutiplicar dos matrices

In [370]:
def MultiplyMatrix(matrix1, matrix2):
    
    if len(matrix1[0])!=len(matrix2):
        return 'No es posible realizar el producto.'
    else:
        resultMatrix = np.zeros([len(matrix1),len(matrix2[0])])
        for i in range(len(matrix1)):
            for j in range(len(matrix2[0])):
                for k in range(len(matrix2)):
                    resultMatrix[i][j] += matrix1[i][k]*matrix2[k][j]
        return resultMatrix

In [371]:
M1 = np.array([[1, 0, 0],[5, 1, 0],[-2, 3, 1]])
M2 = np.array([[4, -2, 1],[0, 3, 7],[0, 0, 2]])

MultiplyMatrix(M1,M2)

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 21.]])

## Punto 4. 
**(Theoretical)** Muestre con detalle que la sustituci´on hacia adelante se expresa como:
$$x_i = b_i + \sum_{j=0}^{i-1} A_{ij}x_j.$$

Esta prueba será realizada por inducción en $i$:

**Caso Base.**

Se tiene que $i=1$. Entonces, $$x_1 = b_1,$$ que corresponde a la primera ecuación del sistema matricial.

**Hipótesis de Inducción.**

Se toma como cierto el caso de $i-1$:
$$x_{i-1} = b_{i-1} + \sum_{j=0}^{i-2} A_{ij}x_j.$$

**Paso Inductivo.**

Para el paso inductivo se supondrá la hipótesis de inducción y se demostrará que es cierto para $i$. Para el sistema $i$ se tiene que


$$ b_{i} = \sum_{j=0}^{i-1} A_{ij}x_i = A_{ii}x_i + \sum_{j=0}^{i-1} A_{ij}x_i$$


## Punto 6. 

In [372]:
def SOR(A, b, x0, omega, itmax=800, tol=1e-9):
    
    x = x0.copy()
    
    for it in range(1,itmax):
        for i in range(A.shape[0]):
            sum_ = 0.
            for j in range(A.shape[1]):
                if j!=i:
                    sum_ += A[i,j]*x[j]
            x[i] = (1-omega)*x[i] + omega*((b[i] - sum_)/A[i,i])
        
        residuo = np.linalg.norm( np.dot(A,x) - b )
        
        if np.allclose(residuo, tol, atol=tol):
            break
    return x, it



In [373]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])
x = np.array([0.,0.,0.])

omega = np.linspace(0.1, 2, 100)
omega_opt = np.inf
iter_opt = 1000-1

for i in omega:
    if SOR(A, b, x, i)[1]< (iter_opt):
        omega_opt = i
        iter_opt = SOR(A, b, x, i)[1]
        
print(omega_opt, iter_opt)

0.9828282828282827 15


## Punto 7. Algoritmo de descomposición

In [374]:
def LUdecomposition(matrix):
    
    n = len(matrix)
    L = np.zeros((n,n))
    U = np.zeros((n,n))

    for i in range(n):
        L[i][i] = 1
        # Upper matrix
        for j in range(i, n):
            for k in range(i):
                U[i][j] = matrix[i][j] - np.sum(U[k][j]*L[i][k])
        # Lower matrix
        for j in range(i + 1, n):
            for k in range(i):
                L[j][i] = (matrix[j][i] - np.sum(U[k][i] * L[j][k]))/U[i][i]
    return L,U

In [375]:
A = np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])

L,U = LU_decomposition(A)
print(' L: \n', L, '\n U: \n', U)

 L: 
 [[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]] 
 U: 
 [[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]


## Punto 9. Método de Jacobi: diagonalización de matrices simétricas.

#### (a) Implemente el método de Jacobi para encontrar los valores y vectores propios de $\mathbb{A}$.

In [376]:
def jacobiDiagonalization(A, itmax=1000, tol=1e-14):
    
    n = A.shape[0]
    D = A.copy()
    VMatrix = np.identity(n)
    
    # SUMA DE LOS ELEMENTOS DISTINTOS A LA DIAGONAL
    # Y LOS ELEMENTOS EN EL TRIANGULO INFERIOR
    res = np.sum(np.abs(np.triu(D, k=1)))
    
    count = 0

    while count<itmax and res>tol:
        # MATRIZ TRIANGULAR SUPERIOR
        DUP = np.triu(D, k=1)
        # INDICE MAYOR EN LA DIAGONAL
        idx = np.argmax(np.abs(DUP))
        p, q = np.unravel_index(idx, DUP.shape)
        
        
        # MATRIZ DE ROTACIÓN R(THETA)
        theta = np.arctan2(2.*D[p, q],(D[q, q] - D[p, p]))/2.
        R = np.identity(n)
        R[p, p] = np.cos(theta)
        R[q, q] = np.cos(theta)
        R[p, q] = -np.sin(theta)
        R[q, p] = np.sin(theta)

        # ACTUALIZACIÓN MATRIZ DE VALORES Y VECTORES PROPIOS
        D = R.T @ D @ R
        VMatrix = VMatrix @ R

        # SUMAR LOS VALORES QUE QUEDARON POR FUERA DE LA DIAGONAL
        res = np.sum(np.abs(np.triu(D, k=1)))
        count += 1

    eigValues = np.diag(D)
    eigVectors = VMatrix / np.linalg.norm(VMatrix, axis=0)
    eigVectors[:,1] = -eigVectors[:,1]
    
    return eigValues, eigVectors

In [377]:
A = np.array([[4,1,1], [1,3,2], [1,2,5]])

print('Con el método de Jacobi:\n\n','- Valores propios: \n', jacobiDiagonalization(A)[0]
      ,'\n\n - Matriz de vectores propios (columna): \n', jacobiDiagonalization(A)[1])

Con el método de Jacobi:

 - Valores propios: 
 [6.8672772  3.39725929 1.73546351] 

 - Matriz de vectores propios (columna): 
 [[ 0.44012262  0.88613215  0.14512713]
 [ 0.43290596 -0.06779913 -0.89888582]
 [ 0.78669213 -0.45844638  0.41345182]]


#### (b) Compare con el resultado que se obtiene de Numpy: np.linalg.eig(A).

In [378]:
print('Con la función predeterminada de numpy:\n\n','- Valores propios: \n', np.linalg.eig(A)[0]
      ,'\n\n - Matriz de vectores propios (columna): \n', np.linalg.eig(A)[1])

Con la función predeterminada de numpy:

 - Valores propios: 
 [6.89510652 3.39729507 1.70759841] 

 - Matriz de vectores propios (columna): 
 [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]


In [379]:
print('Diferencia valores propios: \n', np.linalg.eig(A)[0]-jacobiDiagonalization(A)[0],
     '\n\nDiferencia vectores propios: \n', np.linalg.eig(A)[1]-jacobiDiagonalization(A)[1])

Diferencia valores propios: 
 [ 2.78293166e-02  3.57800416e-05 -2.78650967e-02] 

Diferencia vectores propios: 
 [[-0.00841849 -0.00039651  0.02547158]
 [ 0.06434766 -0.00809426  0.03460633]
 [-0.0341163   0.00050253  0.05974692]]


## Punto 10. Quantum system - ground state.

In [415]:
H = np.array([[1,2,-1], [1,0,1], [4,-4,5]])

In [469]:
# Set the initial guess for the eigenvector (you can choose any nonzero vector)
psi = np.array([1, 1, 1])

# Set the tolerance and maximum number of iterations
tolerance = 1e-8
max_iterations = 1000

# Compute the shifted Hamiltonian and shift value
shift = H[0, 0] + 0.1  # arbitrary shift value
H_shifted = H - shift * np.eye(3)

# Implement the power iteration method
c = 0
for i in range(max_iterations):
    c +=1
    # Compute the QR decomposition of the shifted Hamiltonian
    Q, R = np.linalg.qr(H_shifted)

    # Solve the linear system R*psi_new = Q.T*psi
    psi_new = np.linalg.solve(R, np.dot(Q.T, psi))

    # Compute the eigenvalue estimate
    eigenvalue = np.dot(psi, psi_new) / np.dot(psi, psi)

    # Check for convergence
    print(psi, c)
    if np.linalg.norm(psi - psi_new) < tolerance or np.isnan(psi_new).any():
        print("a",psi, c)
        break

    # Update the eigenvector estimate
    
    psi = psi_new
print("psi:",psi, shift)
# Add the shift value to obtain the true ground state energy
ground_energy = eigenvalue + shift

# Normalize the eigenvector estimate
ground_state = psi_new / np.linalg.norm(psi_new)

# Print the results
print("Ground state energy:", ground_energy)
print("Ground state vector:", ground_state)


[1 1 1] 1
[ 18.65497076 -16.43274854 -35.73099415] 2
[-145.47724086  147.94637666  291.78550665] 3
[ 1505.26827768 -1502.52479345 -3010.09917381] 4
[-14994.01846879  14997.0667846   29988.2671384 ] 5
[ 150006.71345596 -150003.3264384  -300013.30575359] 6
[-1499992.50517803  1499996.26853088  2999985.0741236 ] 7
[ 15000008.34622485 -15000004.1647217  -30000016.65888784] 8
[-1.49999991e+08  1.49999995e+08  2.99999981e+08] 9
[ 1.50000001e+09 -1.50000001e+09 -3.00000002e+09] 10
[-1.5e+10  1.5e+10  3.0e+10] 11
[ 1.5e+11 -1.5e+11 -3.0e+11] 12
[-1.5e+12  1.5e+12  3.0e+12] 13
[ 1.5e+13 -1.5e+13 -3.0e+13] 14
[-1.5e+14  1.5e+14  3.0e+14] 15
[ 1.5e+15 -1.5e+15 -3.0e+15] 16
[-1.5e+16  1.5e+16  3.0e+16] 17
[ 1.5e+17 -1.5e+17 -3.0e+17] 18
[-1.5e+18  1.5e+18  3.0e+18] 19
[ 1.5e+19 -1.5e+19 -3.0e+19] 20
[-1.5e+20  1.5e+20  3.0e+20] 21
[ 1.5e+21 -1.5e+21 -3.0e+21] 22
[-1.5e+22  1.5e+22  3.0e+22] 23
[ 1.5e+23 -1.5e+23 -3.0e+23] 24
[-1.5e+24  1.5e+24  3.0e+24] 25
[ 1.5e+25 -1.5e+25 -3.0e+25] 26
[-1.5e+26

In [465]:
np.isnan(psi_new).any()

True

In [438]:
np.array([1,2,3]).any?

True

## Punto 15. (Particle Physics, Sympy)

In [174]:
gamma0 = sym.Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
gamma1 = sym.Matrix([[0, 0, 0, 1], [0, 0, 1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]])
gamma2 = sym.Matrix([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, 1j, 0, 0], [-1j, 0, 0, 0]])
gamma3 = sym.Matrix([[0, 0, 1, 0], [0, 0, 0, -1], [-1, 0, 0, 0], [0, 1, 0, 0]])

Para todo anticonmutador con indices $\nu$, $\mu$ distintos se tiene una matriz de ceros. Tenga en cuenta las entradas de la relación del anticonmutador

$$ \lbrace\gamma^{\nu},\gamma^{\mu}\rbrace = \lbrace\gamma^{\mu},\gamma^{\nu}\rbrace  $$

ya que se tiene conmutatividad bajo suma. Entonces, todos los posibles casos para la matriz del anticonmutador distintas a la diagonal están dadas por:

In [175]:
gamma0@gamma1+gamma1@gamma0, gamma0@gamma2+gamma2@gamma0, gamma0@gamma3+gamma3@gamma0, gamma1@gamma2+gamma2@gamma1, gamma1@gamma3+gamma3@gamma1, gamma2@gamma3+gamma3@gamma2

⎛⎡0  0  0  0⎤  ⎡0  0  0  0⎤  ⎡0  0  0  0⎤  ⎡0  0  0  0⎤  ⎡0  0  0  0⎤  ⎡0  0  
⎜⎢          ⎥  ⎢          ⎥  ⎢          ⎥  ⎢          ⎥  ⎢          ⎥  ⎢      
⎜⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  
⎜⎢          ⎥, ⎢          ⎥, ⎢          ⎥, ⎢          ⎥, ⎢          ⎥, ⎢      
⎜⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  0  0⎥  ⎢0  0  
⎜⎢          ⎥  ⎢          ⎥  ⎢          ⎥  ⎢          ⎥  ⎢          ⎥  ⎢      
⎝⎣0  0  0  0⎦  ⎣0  0  0  0⎦  ⎣0  0  0  0⎦  ⎣0  0  0  0⎦  ⎣0  0  0  0⎦  ⎣0  0  

0  0⎤⎞
    ⎥⎟
0  0⎥⎟
    ⎥⎟
0  0⎥⎟
    ⎥⎟
0  0⎦⎠

Luego, las entradas distintas a la diagonal, es decir $\lbrace\gamma^{\nu},\gamma^{\mu}\rbrace = 0$ para $\nu\neq\mu$.


Por otro lado, las entradas diagonales están dadas por:

In [177]:
gamma0@gamma0+gamma0@gamma0, gamma1@gamma1+gamma1@gamma1, gamma2@gamma2+gamma2@gamma2, gamma3@gamma3+gamma3@gamma3

⎛⎡2  0  0  0⎤  ⎡-2  0   0   0 ⎤  ⎡-2.0   0     0     0  ⎤  ⎡-2  0   0   0 ⎤⎞
⎜⎢          ⎥  ⎢              ⎥  ⎢                      ⎥  ⎢              ⎥⎟
⎜⎢0  2  0  0⎥  ⎢0   -2  0   0 ⎥  ⎢ 0    -2.0   0     0  ⎥  ⎢0   -2  0   0 ⎥⎟
⎜⎢          ⎥, ⎢              ⎥, ⎢                      ⎥, ⎢              ⎥⎟
⎜⎢0  0  2  0⎥  ⎢0   0   -2  0 ⎥  ⎢ 0     0    -2.0   0  ⎥  ⎢0   0   -2  0 ⎥⎟
⎜⎢          ⎥  ⎢              ⎥  ⎢                      ⎥  ⎢              ⎥⎟
⎝⎣0  0  0  2⎦  ⎣0   0   0   -2⎦  ⎣ 0     0     0    -2.0⎦  ⎣0   0   0   -2⎦⎠

Por los que las entradas de la diagonal están dadas por:
$$\lbrace\gamma^{0},\gamma^{0}\rbrace = 2\cdot \mathbb{I}_{4\times 4},$$
$$\lbrace\gamma^{1},\gamma^{1}\rbrace = -2\cdot \mathbb{I}_{4\times 4},$$
$$\lbrace\gamma^{2},\gamma^{2}\rbrace = -2\cdot \mathbb{I}_{4\times 4},$$
$$\lbrace\gamma^{3},\gamma^{3}\rbrace = -2\cdot \mathbb{I}_{4\times 4}.$$

Luego, 
$$\lbrace\gamma^{\mu},\gamma^{\nu}\rbrace = \left[\begin{array}{cccc}
2 & 0 & 0 & 0	\\
0 & -2 & 0 & 0	\\
0 & 0 & -2 & 0	\\
0 & 0 & 0 & -2
\end{array}\right] = 2\eta^{\mu\nu}\mathbb{I}_{4\times 4}$$


para $\mu,\nu$ que toman los valores de $0,1,2,3$ y $\eta^{\mu\nu}=diag(+1,-1,-1,-1)$.

Verificando así que
$$\lbrace\gamma^{\mu},\gamma^{\nu}\rbrace = \gamma^{\mu}\gamma^{\nu} + \gamma^{\nu}\gamma^{\mu} = 2\eta^{\mu\nu}\mathbb{I}_{4\times 4}.$$